# This script will run tests anytime a pull request is added
name: Plop

on:
  push:
    branches:
      - test-pnpm

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, macos-11, ubuntu-20.04]
    env:
      SIGNAL_ENV: production
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: git config --global core.autocrlf false

      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.15.0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        if: runner.os == 'Windows'

      - name: Setup node for windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          pnpm add -g node-gyp@latest

      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile
      - name: Lint Files
        # no need to lint files on all platforms. Just do it once on the quicker one
        if: runner.os == 'Linux'
        run: pnpm lint-full

      - name: Unit Test
        run: pnpm test
