name: libession-util-nodejs build test

on:
  push:
    branches:
      - main
      - dev
      - groups-chunk-2

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false


      matrix:
        os: [windows-2022, macos-11, ubuntu-20.04]
        include:
          - runs-on: ubuntu-20.04
            compiler: gcc
            gcc: 10

    env:
      SIGNAL_ENV: production
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: git config --global core.autocrlf false

      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install libstdc++-10-dev on ubuntu-20.04
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt install -y libstdc++-10-dev  g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
          sudo update-alternatives --set gcc /usr/bin/gcc-10



      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        if: runner.os == 'Windows'

      - name: Setup node for windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          yarn global add node-gyp@latest

      - name: build libsession-util-nodejs
        shell: bash
        continue-on-error: true
        run:  yarn install --frozen-lockfile --network-timeout 600000

      - name: print cmake files
        shell: bash
        run: cat build/compile_commands.json
